# Generated by Django 5.1 on 2024-08-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
